# Generated by Django 4.1.4 on 2023-02-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='proof_of_education',
            field=models.FileField(default=0, upload_to='mentors/education/'),
            preserve_default=False,
        ),
    ]
