# Generated by Django 4.1.4 on 2023-03-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_applications', '0002_remove_application_mentor_remove_application_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sendername',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
