# Generated by Django 3.2.5 on 2023-03-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_applications', '0003_application_sendername'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='recipientname',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
