# Generated by Django 3.2.5 on 2023-03-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0006_auto_20230324_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
