# Generated by Django 4.1.4 on 2023-03-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mentors', '0002_mentor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='bachelor_degree',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='bachelor_degree_proof',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='biography',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='consultation_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='doctorate_degree',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='doctorate_degree_proof',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='master_degree',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='master_degree_proof',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='specialization',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
