# Generated by Django 4.1.4 on 2023-03-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_mentors', '0003_mentor_bachelor_degree_mentor_bachelor_degree_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='bachelor_degree',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='bachelor_degree_proof',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='doctorate_degree',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='doctorate_degree_proof',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='master_degree',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='master_degree_proof',
        ),
    ]
