# Generated by Django 4.1.4 on 2023-03-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mentors', '0004_remove_mentor_bachelor_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='email',
        ),
        migrations.AddField(
            model_name='mentor',
            name='degree',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='graduation_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mentor_files/{mentor_id}'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='proof_of_degree',
            field=models.ImageField(blank=True, null=True, upload_to='mentor_files/{mentor_id}'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='university',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
