# Generated by Django 4.1.4 on 2023-03-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mentors', '0005_remove_mentor_email_mentor_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
