# Generated by Django 4.1.4 on 2023-03-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_mentors', '0006_mentor_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='specialization',
            new_name='level_of_education',
        ),
    ]
