# Generated by Django 4.1.4 on 2023-03-20 10:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_mentors', '0007_rename_specialization_mentor_level_of_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='proof_of_degree',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document'),
        ),
    ]
