# Generated by Django 4.1.4 on 2023-03-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mentors', '0008_alter_mentor_photo_alter_mentor_proof_of_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
