# Generated by Django 4.1.4 on 2023-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mentors', '0009_alter_mentor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='consultation_cost',
            field=models.CharField(max_length=100),
        ),
    ]
