# Generated by Django 3.2.5 on 2023-03-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mentors', '0010_alter_mentor_consultation_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='proof_of_degree',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
