# Generated by Django 3.2.5 on 2023-03-27 13:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_mentors', '0011_auto_20230327_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='proof_of_degree',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document'),
        ),
    ]
