# Generated by Django 3.2.5 on 2023-03-27 13:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mentors', '0013_auto_20230327_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='proof_of_degree_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='proof_of_degree',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document'),
        ),
    ]
