# Generated by Django 3.2.5 on 2023-03-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_mentors', '0014_auto_20230327_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
